### ISSUE TITLE
What happens in complete bird's eye view?

### ISSUE THREAD

**Issue by Schizo** [krematas/soccerontable#6]
I was wondering, as I didn't see any images from top-down what the result would look like. Btw. do I need the holo-lens to test that?

**Comment by krematas** [comment]
Since we infer depthmaps, going 90 degrees away from the original camera direction (eg top down or extreme side-ways) will reveal that the actual reconstruction is partial. Hololens, will give you the ability to move anywhere, hence seeing these limitations. However, once you have a reconstruction (the per frame meshes) you can visualize it in a renderer (we used blender).
